name: Pull Request Example

on:
  pull_request:
    branches:
      - main
    paths: 
      - _layouts/**
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'npm'

      # Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Install libraries
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run linting
      - name: Run linting
        run: yarn lint

      # Compile code
      - name: Build project
        run: yarn build
        
      # Run tests
      - name: Run tests
        run: yarn test
